### ISSUE TITLE
How to use leafletjs Plugins?

### ISSUE THREAD

**Issue by isuke01** [vue-leaflet/vue-leaflet#212]
Hi,
I tried to use https://oliv.github.io/leaflet-polycolor/
I'm able to add plycolor to map 
Doing:
```js
import L from 'leaflet'; 
import leafletPolycolor from 'leaflet-polycolor';
leafletPolycolor(L);

...
const rideColorLine = L.polycolor(
      createLatLangFromRoute(rwgps.ride_info), 
      {
        colors: createColorsFromRoute(rwgps.ride_info),
        weight: 4
      }
    );

const onMapReady = async () => {
      await nextTick()
      rideColorLine.addTo(poiMapRef.value.leafletObject)
 }
```

But then when I touch/move the map I'm getting console full of errors:
```js
Bounds.js:119 
Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at Bounds.contains (Bounds.js:119:15)
    at NewClass._containsPoint (Polyline.js:310:42)
    at NewClass._handleMouseHover (Canvas.js:398:43)
    at NewClass._onMouseMove (Canvas.js:374:8)
    at HTMLCanvasElement.handler (DomEvent.js:108:13)
```
 
 Is there way to add correctly plugins to Vue-leaflet?

**Comment by AgentXK** [comment]
Did you find the resolution?
