### ISSUE TITLE
Cannot read properties of undefined (reading 'default')

### ISSUE THREAD

**Issue by HamzaAdam** [vue-leaflet/vue-leaflet#278]

**Comment by vinyll** [comment]
Checking the stacktrace, here's where the issue occurs:

```
Me = async (t) => {
  const o = await Promise.all([
    import("leaflet/dist/images/marker-icon-2x.png"),
    import("leaflet/dist/images/marker-icon.png"),
    import("leaflet/dist/images/marker-shadow.png")
  ]);
  delete t.Default.prototype._getIconUrl, t.Default.mergeOptions({
    iconRetinaUrl: o[0].default,
    iconUrl: o[1].default,
    shadowUrl: o[2].default
  });
```

It was working as expected until early this week.
And the the map just disapeared and we suddently read that error.
Note that we experiment that on various browsers, various laptops and various locations.

**Comment by mikeu** [comment]
Hi @vinyll , thanks for the additional context. What versions of vue-leaflet, Leaflet, and Vue are you using? Did anything change in your setup earlier this week, such as applying an update or installing a new package? @HamzaAdam if you have any information at all about the issue then please do provide it as well.

**Comment by vinyll** [comment]
These are all the dependencies we had:
```
  "dependencies": {
    "@gouvfr/dsfr": "^1.8.5",
    "@vue-leaflet/vue-leaflet": "^0.8.1",
    "leaflet": "^1.9.3"
  }
```
(the first dependency is a CSS framework).

That didn't change since.
2 collegues of mine (@SamanthaDangu and another) experimented that issue all of a sudden.
I tried on my end reinstalling the project from a working version and it broke all of a sudden: The page did not display and the error from @HamzaAdam came up.

We spent a few hours investigating from a blank projet until it came out from this package.
The map works if we just use the raw leaflet lib with [the example from the homepage](https://leafletjs.com/) in the same context.
However as soon as we instanciate a `<l-map></l-map>` the error occurs.

**Comment by vinyll** [comment]
Note that updating vue-leafet to `0.8.4` and leaflet to the current latest lead to the same error.

**Comment by mikeu** [comment]
Hmm well that is a pretty minimal set of dependencies for sure, but I so far haven't been able to recreate the issue myself. Here's a [demo running v0.8.4](https://codesandbox.io/s/vl-boilerplate-demo-o73v9e?file=/src/App.vue) showing a successfully rendered `<l-map>` with no errors in the console... Are you able to share a demo project that demonstrates the issue, either as a repo I can clone or on codesandbox, stackblitz, or similar?

**Comment by vinyll** [comment]
That's a good news, yet confusing 🤔 
Here's the project where we meet the issue: https://gitlab.com/incubateur-territoires/startups/agents-intervention (`npm install` + `npm run dev`)
A map should display already at the home page.

**Comment by mikeu** [comment]
I'm not particularly familiar with Nuxt, but it looks as if you might have either enabled SSR somewhere in its config or maybe it does it by default. Or maybe it's doing something else but with a similar effect. Either way, I found that [enabling server-side rendering](https://github.com/vue-leaflet/vue-leaflet/#server-side-rendering-ssr) by adding `:use-global-leaflet="false"` to your `<l-map>` made the map appear for me in your sample app:

![image](https://user-images.githubusercontent.com/605493/221329616-3c31a3d7-85f1-4535-9d13-666891529792.png)

**Comment by HamzaAdam** [comment]
Yes @mikeu is right after adding useGlobalLeaflet=false map works fine. But now I am facing a new problem I am unable to find a way to use @elmarquis gesture handling library with vue leaflet

**Comment by britlog** [comment]
Hi @mikeu, I have just switched from @vue-leaflet/vue-leaflet 0.6.1 (with leaflet 1.8.0) to @vue-leaflet/vue-leaflet 0.8.4 (with leaflet 1.9.3) and got the same error in console :

```
utils.js:70 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Default')
    at resetWebpackIcon (utils.js:70:15)
    at async LMap.vue:247:7
```

However the map is showing with  `:use-global-leaflet="false"` like you said before.
If I switch back to older @vue-leaflet/vue-leaflet and leaflet packages it starts working again.

Thanks

**Comment by MasterSansai** [comment]
I had the exact same issue aswell, using only the quickstart example. 

the solution of adding `:use-global-leaflet="false"` does work, however, what also worked was to add an additional import statement: 
`import L from "leaflet";`

**Comment by mikeu** [comment]
Hi @britlog and @MasterSansai , thank you for reporting that! Are you able to provide a link to a repo that demonstrates the problem, or an online sample of it? Or even just your `package.json` and template—are you also using Nuxt or otherwise working with SSR, or anything else besides Vue, Leaflet, and vue-leaflet? Which version of Vue are you using?

Here is a [demo of the quickstart working without error](https://codesandbox.io/s/vl-boilerplate-demo-o73v9e?file=/src/App.vue) using vue-leaflet 0.8.4, Leaflet 1.9.3, and Vue 3.2.47. I've also been unable to reproduce this problem locally with code and setup similar to the quickstart or the [component playground](https://github.com/vue-leaflet/vue-leaflet/tree/master/src/playground).

**Comment by mikeu** [comment]
After spending some more time trying to reproduce this issue, I've discovered that while `vue create` results in a project that works correctly, `npm create vue@3` creates a project that throws this error when served with `npm run dev`, but which works as expected with `npm run preview`. So I guess Vite is doing something in dev mode sufficiently different from preview mode and from the older Vue CLI approach that it fails to load Leaflet.

To add another wrinkle though, I have a branch locally where I've been working on a conversion to TypeScript. It is ahead of v0.8.4 and uses Vite, and works just fine even in dev mode. I'll keep working on this to try to figure out what's going on, but in the meantime hopefully anyone encountering this issue can use one of the available solutions. Using Vue CLI instead of Vite, using `npm run preview` instead of `npm run dev` with Vite, passing `:use-global-leaflet="false"` to the `<l-map>`, and adding `import "leaflet"` to a Vite project's `main.js` all work, at least for me.

**Comment by picajuicy** [comment]
> After spending some more time trying to reproduce this issue, I've discovered that while `vue create` results in a project that works correctly, `npm create vue@3` creates a project that throws this error when served with `npm run dev`, but which works as expected with `npm run preview`. So I guess Vite is doing something in dev mode sufficiently different from preview mode and from the older Vue CLI approach that it fails to load Leaflet.
> 
> To add another wrinkle though, I have a branch locally where I've been working on a conversion to TypeScript. It is ahead of v0.8.4 and uses Vite, and works just fine even in dev mode. I'll keep working on this to try to figure out what's going on, but in the meantime hopefully anyone encountering this issue can use one of the available solutions. Using Vue CLI instead of Vite, using `npm run preview` instead of `npm run dev` with Vite, passing `:use-global-leaflet="false"` to the `<l-map>`, and adding `import "leaflet"` to a Vite project's `main.js` all work, at least for me.

Thank you a lot! This helps me a lot adding:use-global-leaflet="false" renders my project map successfully.

**Comment by MasterSansai** [comment]
> After spending some more time trying to reproduce this issue, I've discovered that while `vue create` results in a project that works correctly, `npm create vue@3` creates a project that throws this error when served with `npm run dev`, but which works as expected with `npm run preview`. So I guess Vite is doing something in dev mode sufficiently different from preview mode and from the older Vue CLI approach that it fails to load Leaflet.
> 
> To add another wrinkle though, I have a branch locally where I've been working on a conversion to TypeScript. It is ahead of v0.8.4 and uses Vite, and works just fine even in dev mode. I'll keep working on this to try to figure out what's going on, but in the meantime hopefully anyone encountering this issue can use one of the available solutions. Using Vue CLI instead of Vite, using `npm run preview` instead of `npm run dev` with Vite, passing `:use-global-leaflet="false"` to the `<l-map>`, and adding `import "leaflet"` to a Vite project's `main.js` all work, at least for me.

to be more specific I created the project using `npm init vue@latest` as recommended by the official documentation of vue3, maybe that helps finding the issue

**Comment by erickleinde** [comment]
after adding `import L from "leaflet";` it worked again

**Comment by Natanchik89** [comment]
Hello everyone. I am faced with the same problem I have running in two ways. First, there is no error and I use the standard example from the manual as a vps server. But the error appears when I run in OpenServer locally and it helps me  `<l-map :use-global-leaflet="false">`. It's strange why it works differently in the prome and on the local server, but still.

**Comment by Bassadin** [comment]
> after adding `import L from "leaflet";` it worked again

This worked for me, as well. Faced the same issue.

**Comment by Rifaldikn** [comment]
i set to <l-map :use-global-leaflet="false"> but show nothing/no map showing 

<img width="669" alt="image" src="https://github.com/vue-leaflet/vue-leaflet/assets/22056556/ac3d0810-715d-4cdf-8861-9280ee53541b">

**Comment by jlabs** [comment]
I added `:use-global-leaflet="false"` which changed the error from "[Cannot read properties of undefined (reading 'default')](https://github.com/vue-leaflet/vue-leaflet/issues/278#top)" to "Map container not found".

My <l-map>:
```
<l-map ref="map" 
  :use-global-leaflet="false"
  v-model:zoom="zoom" 
  :center="[47.41322, -1.219482]">
```

**Comment by vedmaque** [comment]
This happens because of the Vite. It [prebundles](https://vitejs.dev/guide/dep-pre-bundling.html) commonjs into esmodule, so [this](https://github.com/vue-leaflet/vue-leaflet/blob/master/src/components/LMap.vue#L246) part of code in `LMap` doesn't work as expected.
```
      if (props.useGlobalLeaflet) {
        WINDOW_OR_GLOBAL.L = WINDOW_OR_GLOBAL.L || (await import("leaflet"));
      }
```
Actually, don't know what to do with that, maybe some hardcode (`window.L = window.L.default || window.L`) or do not use umd leaflet import.

**Comment by cerw** [comment]
I am having same issue using Quasar, any resolution for this? Thanks

**Comment by cerw** [comment]
Hi there, 

We are still getting this with newest version: 

```
console-breadcrumbs.js:33 Error: Map container not found.
```

Any ideas? Thanks

**Comment by mikeu** [comment]
Thank you for that pointer, @vedmaque ! Based on that, I have found that this issue can be resolved with a small change to the `vite.config.js` file in the application consuming vue-leaflet. I created a small demo project that was showing the `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Default')` or `Uncaught (in promise) TypeError: t is undefined` issue, then added Leaflet as a [vite included dependency](https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-include):
```
export default defineConfig({
  // ...other options
  optimizeDeps: {
    include: ["leaflet"],
  },
})
```

Unfortunately I have not yet found any way for vue-leaflet itself to automatically enable that option in an application that uses it, but I've had some success putting together a simple vite plugin that does the trick. I'll try to get a new version with that pushed soon, though would still welcome any additional options or suggestions anyone may have!

**Comment by TheEpic-dev** [comment]
I have the same problem with the latest version of Quasar with vite.

Neither `import L from "leaflet";` nor adding `optimizeDeps` to `build.extendViteConf` seem to help.

Only `<l-map :use-global-leaflet="false" ...>` makes the map render for me, but I will make another attempt in some days.

If anyone wants to try to play with the `quasar.config.js` file, here is what I have tried so far:

```javascript
    build: {
      ...,
      extendViteConf (viteConf) {
        // Ensure we don't override any defaults, but also that the objects are defined
        viteConf.optimizeDeps = viteConf.optimizeDeps || {};
        viteConf.optimizeDeps.entries = viteConf.optimizeDeps.entries || [];
        viteConf.optimizeDeps.entries.push("leaflet");
        // the above adds 'leaflet' to optimizeDeps.entries in quasar inspect but the exception still gets raised
        viteConf.optimizeDeps.include = viteConf.optimizeDeps.include || [];
        viteConf.optimizeDeps.include.push("leaflet");
       // the above gives me the keys ['entries', 'include'] in optimizeDeps according to quasar inspect, but the exception still gets thrown
      },
    },
```

**Comment by ruilvo** [comment]
I made it work in Quasar with the following workaround:

Create a boot file (I called it `leaflet.ts`).

Add the following contents:

```ts
import { boot } from 'quasar/wrappers';

import L from 'leaflet';

export default boot(() => {
  globalThis.L = L;
});
```

Do not forget to add the file to `quasar.config.js`:

```js
// ...
    // app boot file (/src/boot)
    // --> boot files are part of "main.js"
    // https://v2.quasar.dev/quasar-cli-vite/boot-files
    boot: ['axios', 'loading-bar', 'leaflet'],       // <--- HERE
```

PS:

You can also simplify the usage of the CSS file (if you want), by adding to the global CSS:

Also in `quasar.config.js`:

```js
    // https://v2.quasar.dev/quasar-cli-vite/quasar-config-js#css
    css: ['app.scss', '~leaflet/dist/leaflet.css'],
```

and never need to explicitly import it again.

**Comment by ruilvo** [comment]
To be clear, and for everybody else, it also works if you just add the lines 

```ts
import L from 'leaflet';

globalThis.L = L;
```

In the component you're using vue-leaflet on.

**Comment by nossienl** [comment]
if you are working on nuxt 3 with the leaflet plugin

add it to  the options of the LMap

 ```<LMap ref="map" :options="options" :zoom="zoom" @ready="mapInitialized">```

```
const options = {
  attributionControl: false,
  dragging: !isMobile,
  useGlobalLeaflet: false,
};
```

**Comment by harriskhalil** [comment]
i am also facing an issue here in vue 3 with leaflet. On  page change (moving from one page to an other when i open the insepect window) 
i get these errors

> TypeError: Cannot use 'in' operator to search for '_leaflet_id' in undefined

> leaflet-src.esm-CFZRPG3U.js?v=1b0ac174:1562 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_leaflet_pos')

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'appendChild')

but when i close the inspect window and then move from one page to another nothing happend and i see maps getting renederd.
````
<template>
    <div style="height:60vh; width:100%">
        <l-map :useGlobalLeaflet="false" :center="mapCenter" v-model:zoom="zoom">
            <l-tile-layer
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                layer-type="base"
                name="OpenStreetMap"
            ></l-tile-layer>
            <l-marker :lat-lng="markerPosition" />
        </l-map>
    </div>
    
````

```
`<script>
import "leaflet/dist/leaflet.css";
import { LMap, LTileLayer, LMarker, LGeoJson } from "@vue-leaflet/vue-leaflet";

export default {
    components: {
        LMap,
        LTileLayer,
        LMarker,
        LGeoJson,
    },
    data() {
        return {
            mapCenter: [47.0464128, 15.7481856],
            zoom: 20,
            markerPosition: [47.0464128, 15.7481856],
        };
    },
};
</script>
`
```

**Comment by davidMZL** [comment]
`<LMap
              v-model="zoom"
              :zoom="zoom"
              :center="center"
              :options="options"
            >
              <LTileLayer
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              />`
              and
              `const options = {
      attributionControl: false,
      useGlobalLeaflet: false,
    };`
I am trying this, but I keep getting this error: 
![image](https://github.com/user-attachments/assets/dfa98073-7c2d-48f8-929d-e438d946d346)
I have also tried with:
`<LMap
              :use-global-leaflet="false"
              v-model="zoom"
              :zoom="zoom"
              :center="center"
            >
              <LTileLayer
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              />`
             but I have the same error on the console. And I'm using Vue 3 and Vite

**Comment by laughablejulio** [comment]
@ruilvo https://javascripter.space/questions/is-it-possible-to-convert-a-leaflet-marker-into-a-nuxt-link-function
