### ISSUE TITLE
Use a method on a polyline

### ISSUE THREAD

**Issue by msslgomez** [vue-leaflet/vue-leaflet#301]
How can I use a method from leaflet on a polyline? https://leafletjs.com/reference.html#polyline-closestlayerpoint

I tried this but I get some errors
```
<template>
    <div class="h-full w-full rounded overflow-hidden shadow">
        <l-map v-if="get_zoom && get_bounds && get_center" :zoom="get_zoom" :bounds="get_bounds"
               :center="get_center" ref="map" id="map" class="z-0">
            <l-tile-layer :url="url" :attribution="attribution"/>

            <div>
                <l-polyline @mouseover="handleReady" ref="line" :lat-lngs="get_coordinates_route" color="#1a7d9c" :opacity="0.5"></l-polyline>
            </div>
        </l-map>
    </div>
</template>
<script>
import {latLng, icon, divIcon, latLngBounds} from "leaflet";
import {
    LMap,
    LTileLayer,
    LMarker,
    LPopup,
    LIcon,
    LPolyline,
    LTooltip,
    LControl,
    LCircle,
    LControlScale
} from "vue2-leaflet";

export default {
    name: 'map-component',
    components: {
        TriangleDownIcon,
        TriangleUpIcon,
        CheckIcon,
        ProgressIcon,
        LMap,
        LTileLayer,
        LMarker,
        LPopup,
        LTooltip,
        LControl,
        LPolyline,
        LIcon,
        LCircle,
        LControlScale
    },
    data() {
        return {
            attribution:
                '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
            url:
                'https://cartodb-basemaps-{s}.global.ssl.fastly.net/rastertiles/voyager/{z}/{x}/{y}.png',

            icon: icon({
                iconUrl: "/assets/markers/mark_avatar.png",
                iconSize: [20, 20],
                iconAnchor: [20, 20],
                popupAnchor: [-10, -20],
            }),
        };
    },
    methods: {
        handleReady() {
            console.log('here', this.$refs.line.mapObject.closestLayerPoint());
        },
    },
}
</script>
```

When hovering over the line I get two errors
```
[Vue warn]: Error in v-on handler: "TypeError: Cannot read properties of undefined (reading 'x')"

found in

---> <LPolyline>
       <LMap>
         <MapComponent> at resources/js/shared/Components/GPS/MapComponent.vue
           <TenantLayout> at resources/js/layouts/TenantLayout.vue
             <GpsIndex> at resources/js/Pages/Tenant/GPS/GpsIndex.vue
               <Inertia>
                 <Root>


TypeError: Cannot read properties of undefined (reading 'x')
    at _sqClosestPointOnSegment (app.js:42966:13)
    at NewClass.closestLayerPoint (app.js:44960:20)
    at VueComponent.handleReady (app.js:25743:53)
    at invokeWithErrorHandling (app.js:183247:26)
    at NewClass.invoker (app.js:183572:14)
    at NewClass.handler (app.js:39450:15)
    at NewClass.fire (app.js:37369:13)
    at NewClass._fireDOMEvent (app.js:41184:17)
    at NewClass._handleDOMEvent (app.js:41141:10)
    at HTMLDivElement.handler (app.js:39450:15)
```

What am I doing wrong? How can I get the closest point on the line to the mouse?

**Comment by Vectorial1024** [comment]
I looked at:

```ts
import {
    LMap,
    LTileLayer,
    LMarker,
    LPopup,
    LIcon,
    LPolyline,
    LTooltip,
    LControl,
    LCircle,
    LControlScale
} from "vue2-leaflet";
```

It seems you are using `vue2-leaflet` for Vue 2 (https://github.com/vue-leaflet/Vue2Leaflet), which is not the same as the library in this repo. This repo is `@vue-leaflet/vue-leaflet` for Vue 3 (https://github.com/vue-leaflet/vue-leaflet).

Assuming you indeed want to use the Vue 3 version not the Vue 2 version, at least you should do this instead:

```ts
import {
// ...
} from "@vue-leaflet/vue-leaflet";
// you are now using the Vue 3 version of the library
```

Then, you can continue debugging the rest of your code.

**Comment by msslgomez** [comment]
@Vectorial1024 Sorry, can't believe I mixed that up. I am using the vue2 version.
