### ISSUE TITLE
LMap broken since vue@3.3.5 (and 3.3.6, 3.3.7)

### ISSUE THREAD

**Issue by Maximvdw** [vue-leaflet/vue-leaflet#355]
Last week Vue updated to 3.3.5. This immediately broke a lot of things and a fix was created in 3.3.6.
However, the only thing still broken is vue-leaflet. 

The following error is thrown at runtime:
```
Uncaught (in promise) Error: Map container not found.
    at NewClass._initContainer (leaflet-src.js:4205:1)
    at NewClass.initialize (leaflet-src.js:3249:1)
    at new NewClass (leaflet-src.js:302:1)
    at createMap (leaflet-src.js:4863:1)
    at eval (vue-leaflet.es.js:1363:1)
```

Checking in the development console I can find the map element, so my assumption is that somehow the creation of the leaflet map is called too early.

Reverting to vue@3.3.4 fixes the issue.

**Comment by Maximvdw** [comment]
can confirm this issue still exists in the 3.3.7 release of Vue released today

**Comment by jousepo** [comment]
Version 0.7.x of vue-leaflet works witth these versions

**Comment by 121593** [comment]
Issue solved with `vue@3.3.9`
