### ISSUE TITLE
Lmap not working after upgrading vue2 to vue 3

### ISSUE THREAD

**Issue by SnehalDevkar** [vue-leaflet/vue-leaflet#367]
I'm migrating vue2 project to vue3 with below configuration

**"vue": "^3.3.8",
"leaflet": "^1.7.1",
"@vue-leaflet/vue-leaflet": "^0.6.1"**

Not getting any issue in the build. But graph is not loading on to the screen and getting below exception in console.

LMap.vue:411  Uncaught (in promise) TypeError: this.$slots.default is not a function
    at Proxy.render (LMap.vue:411:32)
    at Proxy.compatRender (vue.esm-bundler.js:5072:21)
    at renderComponentRoot (vue.esm-bundler.js:2931:16)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-bundler.js:9277:26)
    at ReactiveEffect.run (vue.esm-bundler.js:521:19)
    at instance.update (vue.esm-bundler.js:9336:16)
    at callWithErrorHandling (vue.esm-bundler.js:1744:32)
    at flushJobs (vue.esm-bundler.js:1952:9)
        
![image](https://github.com/vue-leaflet/vue-leaflet/assets/20985668/fd92db5f-5d20-49ed-92ed-292f89814132)

 Any help would be greatly appreciated.

Thank you.

**Comment by ChuTungLinh** [comment]
just out of cruiosity why is there a need for "this.$slot.default" (im kinda new to vue)

**Comment by AbdellahRsmouki** [comment]
Hello @ChuTungLinh @SnehalDevkar , I am migrating from vue 2 to vue 3 and I have the same issue using "@vue-leaflet/vue-leaflet": "^0.9.0".
Did you find any solution to this error ?

**Comment by ChuTungLinh** [comment]
> Hello @ChuTungLinh @SnehalDevkar , I am migrating from vue 2 to vue 3 and I have the same issue using "@vue-leaflet/vue-leaflet": "^0.9.0". Did you find any solution to this error ?

While i did manage to make my map worked in vue 3 typescript but i dont use "this.$slot.default" so i cant really help with this. But i think this is more of a Vue problem rather than a leaflet problem, maybe you can search for solution overthere ?

**Comment by mateus-lanuce** [comment]
I have the same problem. is caused by vue on versions: vue ^3.15.
