### ISSUE TITLE
An error occurred in use of CDN (Failed to resolve module specifier 'leaflet')

### ISSUE THREAD

**Issue by solitary-pocky** [vue-leaflet/vue-leaflet#378]
I had used VueLeaflet by CDN, but got an error below:

```
Uncaught (in promise) TypeError: Failed to resolve module specifier 'leaflet'
    at vue-leaflet.umd.min.js:7:21549
    at vue.global.js:4401:90
    at callWithErrorHandling (vue.global.js:1768:21)
    at callWithAsyncErrorHandling (vue.global.js:1775:19)
    at hook.__weh.hook.__weh (vue.global.js:4381:21)
    at flushPostFlushCbs (vue.global.js:1941:43)
    at render (vue.global.js:8153:9)
    at mount (vue.global.js:5453:15)
    at app.mount (vue.global.js:11060:21)
    at userCodeAppPanel:113:11
```

I had used VueLeaflet as below:

```
    <script src="https://cdn.jsdelivr.net/npm/@vue-leaflet/vue-leaflet@0.10.1/dist/vue-leaflet.umd.min.js"></script>
    <script>
      const { createVuetify, useDisplay } = Vuetify;
      const vuetify = createVuetify({
        theme: {
          defaultTheme: 'light'
        }
      });
      const { ref, createApp, onMounted, computed, watch } = Vue;
      const {LMarker, LMap, LTileLayer} = window['vue-leaflet'];
      const vueApp = {
        components: {
          LMarker,
          LMap,
          LTileLayer,
        },
        setup() {
          // ---

          onMounted(() => {
            // ---
          });

          return {
            // ---
          };
        }
      };

      const app = createApp(vueApp);
      app.use(vuetify);
      app.mount("#app");
    </script>
```

If there are any solutions and someone tells me, I'll be very happy.

Thanks.

**Comment by nikbpetrov** [comment]
+1

For what it's worth, I used this to import components (instead of the `<script src="https://cdn.jsdelivr.net/npm/@vue-leaflet/vue-leaflet@0.10.1/dist/vue-leaflet.umd.min.js"></script>`):
```html
<script type="module">
    import * as vueLeafletvueLeaflet from 'https://cdn.jsdelivr.net/npm/@vue-leaflet/vue-leaflet@0.10.1/+esm'
    const { LMap, LTileLayer } = vueLeafletvueLeaflet
    //{rest of your code...}
</script>
```

which does not give that error, but does not show anything for me. My full code, if interested and you can get it to work:

```html
<script src="https://code.jquery.com/jquery-3.7.1.min.js"
    integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

<script src="https://unpkg.com/vue@3.2.33/dist/vue.global.js"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

<div id="app">
    <h1>Interactive Map with Image Tiles</h1>

    <div style="height:600px; width:800px">
        <l-map ref="map" v-model:zoom="zoom" :center="[47.41322, -1.219482]" style="height:100%; width:100%;">
            <l-tile-layer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" layer-type="base"
                name="OpenStreetMap"></l-tile-layer>
        </l-map>
    </div>
</div>

<script type="module">
    import * as vueLeafletvueLeaflet from 'https://cdn.jsdelivr.net/npm/@vue-leaflet/vue-leaflet@0.10.1/+esm'
    const { LMap, LTileLayer } = vueLeafletvueLeaflet

    const app = Vue.createApp({
        components: {
            LMap,
            LTileLayer
        },
        data() {
            return {
                zoom: 2,
            }
        },
        computed: {
        },
        methods: {
        },
        mounted() {
        }
    })
    app.mount('#app')
</script>
```

**Comment by dmvstar** [comment]
I try to use this solution 
[REF](https://github.com/vue-leaflet/vue-leaflet/issues/378#issuecomment-2147383707)
My full page code 
```html
<html>

<head>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/vue@3.2.33/dist/vue.global.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
</head>

<body>

    <div id="app">
        <h1>Interactive Map with Image Tiles</h1>

        <div style="height:600px; width:800px">
            <l-map ref="map" v-model:zoom="zoom" :center="[47.41322, -1.219482]" style="height:100%; width:100%;">
                <l-tile-layer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" layer-type="base"
                    name="OpenStreetMap"></l-tile-layer>
            </l-map>
        </div>

    </div>

    <script type="module">
        import * as vueLeafletvueLeaflet from 'https://cdn.jsdelivr.net/npm/@vue-leaflet/vue-leaflet@0.10.1/+esm'
        const { LMap, LTileLayer } = vueLeafletvueLeaflet

        const app = Vue.createApp({
            components: {
                LMap,
                LTileLayer
            },
            data() {
                return {
                    zoom: 2,
                }
            },
            computed: {
            },
            methods: {
            },
            mounted() {
            }
        })
        app.mount('#app')
    </script>

</body>

</html>
``` 

I have a warning and l-map component do not show.

`[Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. 
  at <LMap ref="map" zoom=2 onUpdate:zoom=fn<onUpdate:zoom>  ... > 
  at <App>`

If there are any solutions and someone tells me, I'll be very happy.

Thanks.
